server:
  port: 8761

Spring:
  application:
    name: ead-service-registry
  output:
    ansi:
      enabled: Always

ead:
  serviceRegistry:
    username: ead-admin  #local/dev
    password: ead-secret #local/dev

eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
    service-url:
      defaultZone: 'http://ead-admin:ead-secret@localhost:8761/eureka'